import Head from "next/head";
import { useRecoilState,atom } from "recoil";
// import { modalState } from "../atoms/ModalAtom";
import Feed from "../components/Feed";
import Header from "../components/Header";
import Modal from "../components/Modal";

const modalState = atom({
  key: "modalState",
  default: false,
});

export default function Home() {
  const [open, setOpen] = useRecoilState(modalState);
  return (
    <div className="bg-gray-50 h-screen overflow-y-scroll scrollbar-hide">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Feed />
      {open && <Modal />}
    </div>
  );
}
